### ISSUE TITLE
Feature request: Add white list, split upstream dns server in different route

### ISSUE THREAD

**Issue by cnmade** [AdguardTeam/dnsproxy#195]
This is for CDN special usage.

For example, we know weibo and taobao and douyin is chinese primary hot website.
we can put them in whitelist, then these domain can forward to chinese hot dns provider, like 114dns, aliyun dns, tencent dns.
to gain better CDN response.

The other any domain , not in the whitelist, can be forward as usual.

**Comment by cnmade** [comment]
example config file
```yml
domain_whitelist:
    - upstream: 114.114.114.114
       domain:  
           - taobao.com
           - alibaba.com
           - weibo.com
    - upstream:  208.67.222.222
      domain: 
           - google.com
           - twitter.com
```

![image](https://user-images.githubusercontent.com/278153/147378895-59f1193d-4bc8-423a-abe4-69dcb958f1ca.png)
