### ISSUE TITLE
Fallback-servers with DoH/DoT?

### ISSUE THREAD

**Issue by iJorgen** [AdguardTeam/dnsproxy#250]
Is it possible to setup DoH or DoT on the fallback-servers or only unencrypted queries is possible?

**Comment by ameshkov** [comment]
Hi! Any type of resolver may be a fallback

**Comment by iJorgen** [comment]
I found in the code that it is possible, but you need to specify the DoH/DoT servers by using IP (since DNS-resolution don't work) so it won't work for me since I need to specify a custom URL for DoH/DoT including my configuration-id.

Will go with unencrypted DNS for my fallback-server, since it's the last chance to get an answer when upstream-servers fails.

**Comment by ameshkov** [comment]
Could it be that you mean bootstrap servers and not fallback servers?

**Comment by iJorgen** [comment]
Aaah, you are correct. It was under "Bootstrap" I read that. :-)

`// Validate the bootstrap resolver. It must be either a plain DNS resolver.
// Or a DoT/DoH resolver with an IP address (not a hostname).`

Do fallback servers use the Bootstrap servers to resolve, if all upstream-servers are failing? I mean if I specified "tls://dns.adguard-dns.com" under fallback and all upstream-servers are down. How does it resolve "dns.adguard-dns.com" then?!

**Comment by samlux04** [comment]
> Aaah, you are correct. It was under "Bootstrap" I read that. :-)
> 
> `// Validate the bootstrap resolver. It must be either a plain DNS resolver. // Or a DoT/DoH resolver with an IP address (not a hostname).`
> 
> Do fallback servers use the Bootstrap servers to resolve, if all upstream-servers are failing? I mean if I specified "tls://dns.adguard-dns.com" under fallback and all upstream-servers are down. How does it resolve "dns.adguard-dns.com" then?!

Bootstrap used to resolve all DNS hostname.
```yaml
bootstrap:
  - "tls://1.0.0.1"
  - "https://1.1.1.1/dns-query"
  - "https://8.8.8.8/dns-query"
upstream:
  - "tls://dns.adguard.com"
  - "quic://dns.nextdns.io"
fallback:
  - "tls://doh.tiar.app"
  - "https://1.1.1.1/dns-query' # just in case when other down
```
